services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - saasnet
    depends_on:
      - database
      - redis

  nginx:
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    container_name: nginx
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .docker/nginx/www:/var/www/certbot
      - .docker/nginx/certs:/etc/letsencrypt
      - .docker/nginx/logs:/var/log/nginx
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - saasnet
    depends_on:
      - app

  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - saasnet

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - .redis:/data
    networks:
      - saasnet

networks:
  saasnet:
    driver: bridge
    name: saasnet

volumes:
  .postgres:
  .redis:
